### ISSUE TITLE
Dirty wordlist - inconsistence rules in output

### ISSUE THREAD

**Issue by viktorheli** [lakiw/pcfg_cracker#15] opened 2019-08-23 06:28 UTC
Thank you very much for the original project. It helps a lot in my research on neural networks.
There is one issue that I encountered.

In real life, most wordlists contain different non-printable characters.
After training "python3 trainer.py -t test-list -r test-list -c 0.8" on such a wordlist
the training process is successful. But pcfg_guesser.py give error:
python3 pcfg_guesser.py -r test-list -s test-list -d

Version: 4.0

Loading Ruleset: test-list

list index out of range
Error loading other/special terminals
Traceback (most recent call last):
  File "pcfg_guesser.py", line 239, in main
    debug = program_info['debug']
  File "/home/vik/torch7/pcfg_cracker/lib_guesser/pcfg_grammar.py", line 56, in __init__
    self.grammar, self.base, self.ruleset_info = load_grammar(rule_name, base_directory, version, skip_brute)
  File "/home/vik/torch7/pcfg_cracker/lib_guesser/grammar_io.py", line 67, in load_grammar
    raise Exception
Exception
Exception: 
Exiting

I am not a cool Python programmer. :( I could not fully understand the code for writing the patch. Sorry. However, I found out that the file name in the Rules / <you rules> directory before dot, for example, 1.txt or 10.txt, means length - in this case length is 1 or 10.

If our wordlist is not clean enough, we get in the rules, for example, this:
less Rules/test-list/Other/1.txt (rule length = 1)
\`        0.8587246257945458\
\(       0.04039368464219807\
\'       0.028296083657986467\
)       0.026655730982161164\
\-       0.01250768915316793\
\^A      0.005331146196432233 - wrong length\
\]       0.003485749436128768\
\^B      0.003280705351650605 - wrong length\
\^D      0.003280705351650605 - wrong length\
\^C      0.002870617182694279 - wrong length\
\?       0.0026655730982161163\
\<A9>    0.002460529013737954 - wrong length\
\.       0.0016403526758253025\
\^E      0.0016403526758253025 - wrong length\
\"       0.0008201763379126512\
\!       0.0006151322534344885\
\<87>    0.0006151322534344885 - wrong length\
\^H      0.0006151322534344885 - wrong length\
\^F      0.0006151322534344885 - wrong length\
\<AE>    0.0004100881689563256 - wrong length\
\<A2>    0.0004100881689563256 - wrong length\
\<A8>    0.0004100881689563256 - wrong length\
\<A7>    0.0004100881689563256 - wrong length\
\[       0.0004100881689563256\
\:       0.0004100881689563256\
\,       0.0004100881689563256\
\#       0.0004100881689563256\
\<A3>    0.0002050440844781628 - wrong length

After deleting lines with "wrong length" from the file, pcfg_guesser.py may work.
But there are many rules on large wordlists and it’s very long to delete manually.

As a temporary solution, you can use:
cat \<you wordlist>\ | tr -cd '[:print:]\n' > \<new wordlist>\
This solution is not perfect. This command will remove all non-English characters.

For example:
echo "珠珠" | tr -cd '[:print:]\n'
<is empty>

The correct solution is to check the length of the rule before adding it, and discard it if the length does not match in pcfg_guesser.py. The second solution is to discard incorrect rules at the training stage in trainer.py. 

Link to test-list:
https://www.dropbox.com/s/wr3wdw9vpc95x42/test-list?dl=0

Link to "problem rules":
https://www.dropbox.com/s/0divz5mmgrntb7x/test-list.tar.gz?dl=0

**Comment by lakiw** [comment] 2019-08-23 13:39
Thank you very much for the excellent issue report! I'll download and test your dataset later tonight, but in the meantime I think I know what the problem is, and a fix is available in the 4.1 branch:  

https://github.com/lakiw/pcfg_cracker/tree/4.1

I'm planning on pushing the 4.1 branch to main sometime this weekend after I do some more testing. The issue actually appears to be that Python interprets certain characters like 'FileSeperator" (Hex: 0x1C), as a newline, so it'll print out 0x1C on one line and the probability on the next, which the guesser reads as a malformed rules file and throws and exception. The fix in 4.1 is applied to both the trainer, (so that value and related ones are not trained upon), and the guesser (to gracefully handle when those types of errors sneak into a ruleset).

As to your troubleshooting, I really appreciate it! As a FYI, sometimes when viewing UTF-8 and other file encodings in a text viewer, the text viewer will display one character values as multiple characters. I suspect that's what you are seeing with the multicharacter values, though I won't be able to verify that until I actually take a look at your dataset. Once again though, excellent issue report, and it's always a learning experience for me when other people try to use my code and it breaks in new and interesting ways.

**Comment by viktorheli** [comment] 2019-08-23 15:29
Thanks for your reply.
I tested branch 4.1 with a test wordlist from the link above.
Here is the debug log:
python3 pcfg_guesser.py -r test-list -s test-list -d
Version: 4.0.1

Loading Ruleset: test-list

Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/2.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/2.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/2.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/3.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/3.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/5.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/6.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/7.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/7.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/7.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/8.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/8.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/8.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/10.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/14.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/18.txt
list index out of range
Ignorning line and continuing
Exception parsing file: /home/vik/torch7/pcfg_cracker-4.1/Rules/test-list/Other/20.txt
list index out of range
Ignorning line and continuing
Error reading the OMEN ruleset


trainer.py works without any errors.

**Comment by viktorheli** [comment] 2019-08-23 17:15
In my opinion, the problem is with non-printable characters that are often found in wordlists.
As a solution, we can try these options:
- the user himself will prepare a wordlist - delete non-printable characters;
- remove all non-printable characters from strings at the training stage.

But we need to understand that deleting non-printable characters can not always give a good result, since strings can be in different encodings.

I tried using a simple Python script to remove non-printable characters. It works fine on a test sheet. Also tested it on mixed text in utf8 encoding.
Here is a script that might come in handy for someone:
#!/usr/bin/python3.6
#-*- coding: utf-8 -*-
import sys


for stringin in sys.stdin:
        text = stringin.replace("\t","<prd1>")
        output = "".join(c for c in text if c.isprintable())
        text1 = output.replace("<prd1>","\t")
        print(text1.strip())

**Comment by lakiw** [comment] 2019-08-24 00:10
Thanks! I finally got around to downloading your wordlist + rules. Thank you so much for making those available as that was very helpful. I saw what you posted above when I ran your rules set, with OMEN failing to load. That being said, when I retrained the ruleset from the dirty wordlist you provided and the 4.1 branch, I was able to run the resulting guessing session without any errors, which implies the fixes I made the the trainer in 4.1 were effective. Now, I probably need to loop around back to the OMEN loader and make it more resilient to loading junk for some of its n-grams, but I think the problem is mostly fixed. You should hopefully be able to replicate the fix as well if you retrain your ruleset using the 4.1 branch.

**Comment by lakiw** [comment] 2019-08-25 01:50
My apologies, I thought I had pushed some additional changes when I hadn't. The new 4.1 branch should have the fixes I was testing with.

**Comment by viktorheli** [comment] 2019-08-25 05:08
Good day.
I tested the 4.1 branch. Everything works perfectly.
I continue to use this wonderful tool in my research work.
Thank you very much!

**Comment by lakiw** [comment] 2019-08-25 22:14
Awesome! I just committed the 4.1 branch to main: 918c04c0d9190233cac9744e736fce7541163258
I'm going to close this issue for now, but if it pops up again please don't hesitate to re-open it. Also if you run into any other problems or have any questions feel free to create new issues for them.

**Closed by lakiw** 2019-08-25 22:14 UTC
